[package]
name = "phone_data"
version = "0.1.0"
authors = ["Kurisu <lucifer994@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.1.0"
serde = "1.0.143"
serde_derive = "1.0.143"
failure = "0.1.8"
lazy_static = "1.4.0"
